version: '3.7'

services:
  postgresql:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: stonk
      POSTGRES_PASSWORD: overflow
      POSTGRES_DB: stonkoverflow
    tmpfs:
      - /tmp
      - /run

volumes:
  pgdata:
    driver: local

